package mobi.neuerung.Wrapper;

public class ElementWrapper {


	public String ScreenName;
	public String Number;
	public String Code;
	public String Section;
	public String Type;
	public String Title;
	public String Bitmap;
	public String OnClick;
	public String width;
	public String height;
	public String left;
	public String middle;
	public String right;
	public String leftper;
	public String rightper;
	public String middleper;
	public String leftbgColor;
	public String midbgColor;
	public String rightbgColor;
	public String leftbgImage;
	public String midbgImage;
	public String rightbgImage;
	public String distleft;
	public String disttop;
	public String leftClick;
	public String rightClick;
	public String bgcolor;
	public String selectedBgcolor;
	public String txtColor;
	public String body="";
	public String mailto="";
	public String subject="";
	public String font;
	public String fontStyle;
	public String fontSize;
	public String fontColor;
	public String SubTitlefont;
	public String subtitlefontStyle;
	public String subtitlefontSize;
	public String subtitlefontColor;
	public String leftscalefactor;
	public String rightscalefactor;
	public String midscalefactor;
	public String subTitle;
	public String maxline;
	public String TitleGravity;
	public String SubTitleGravity;
	public String xper;
	public String yper;
	public String shareText;
	public String ImageWidth;
	public String ImageHeight;
	public String TextWidth;
	public String TextHeight;
	public String Link;
	public String dividerColor;
	public String ImageSet;
	public String switcherTimer;
	public String TextMode;
	public String TextTransColor;
	public String ImageMode = "";
	public String TopMargin;
	public String ImageUrlSet;
	public String circleColor;
	public String Datefont;
	public String DatefontStyle;
	public String DatefontSize;
	public String DatefontColor;
	public String Timefont;
	public String TimefontStyle;
	public String TimefontSize;
	public String TimefontColor;
	public String ReadNewsfont;
	public String ReadNewsfontStyle;
	public String ReadNewsfontSize;
	public String ReadNewsfontColor;
	public String Linkfont;
	public String LinkfontStyle;
	public String LinkfontSize;
	public String LinkfontColor;
	public String Datebg;
	public String shareVisiblity;
	public String textChangeSizeVisiblity;
	public String cc="";
	public String bcc="";
	public String dialogText;
	public String dialogOnOff;
	public String instance="";


}
